<?php
/**
 * Created by PhpStorm.
 * User: kalyan
 * Date: 1/6/15
 * Time: 2:13 PM
 */

namespace Bux\UserBundle\DataFixtures\ORM;

use Bux\UserBundle\Entity\Membership;
use Bux\UserBundle\Entity\ReferralPrice;
use Bux\UserBundle\Entity\RentReferral;
use Bux\UserBundle\Entity\WithdrawSettings;
use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;

/**
 * Class LoadMembershipData
 *
 * @package Bux\UserBundle\DataFixtures\ORM
 */
class LoadMembershipData extends AbstractFixture implements OrderedFixtureInterface
{
    /**
     * {@inheritDoc}
     */
    public function load(ObjectManager $manager)
    {
//        $membership = new Membership();
//        $membership->setName('Lollipop');
//        $membership->setPrice(0.00);
//        $membership->setDuration(30);
//        $membership->setClick(30);
//        $membership->setVideoClick(30);
//        $membership->setPollClick(30);
//        $membership->setMaxClickInDay(0);
//        $membership->setMaxVideoClickInDay(0);
//        $membership->setMaxPollClickInDay(0);
//        $membership->setRefClick(10);
//        $membership->setRefVideoClick(10);
//        $membership->setRefPollClick(10);
//        $membership->setRefLimit(5);
//        $membership->setRentedRefLimit(100);
//        $membership->setInstPayment(false);
//        $membership->setPurchaseComission(0);
//        $membership->setUpgradeComission(0);
//        $membership->setRefDeletionCost(0);
//        $membership->setActive(true);
//        $manager->persist($membership);
//        $this->addReference('lollipop', $membership);
//        $withdrawSettings = new WithdrawSettings();
//        $withdrawSettings->setMembership($membership);
//        $withdrawSettings->setCashoutTime(3);
//        $withdrawSettings->setMaxInDay(100);
//        $withdrawSettings->setMinPayout(10);
//        $manager->persist($withdrawSettings);
//        $rentReferral = new RentReferral();
//        $rentReferral->setMembership($membership);
//        $rentReferral->setRefLimit(0);
//        $rentReferral->setRefPack(5);
//        $rentReferral->setRecycleCost(10);
//        $rentReferral->setRefTime(3);
//        $manager->persist($rentReferral);
//        $price = new ReferralPrice();
//        $price->setMinRef(0);
//        $price->setMaxRef(250);
//        $price->setMonthly(0.01);
//        $price->setAutopay(0.02);
//        $price->setMembership($membership);
//        $manager->persist($price);
//        $price = new ReferralPrice();
//        $price->setMinRef(251);
//        $price->setMaxRef(500);
//        $price->setMonthly(0.01);
//        $price->setAutopay(0.02);
//        $price->setMembership($membership);
//        $manager->persist($price);
//        $price = new ReferralPrice();
//        $price->setMinRef(501);
//        $price->setMaxRef(750);
//        $price->setMonthly(0.01);
//        $price->setAutopay(0.02);
//        $price->setMembership($membership);
//        $manager->persist($price);
//        $price = new ReferralPrice();
//        $price->setMinRef(751);
//        $price->setMaxRef(1000);
//        $price->setMonthly(0.01);
//        $price->setAutopay(0.02);
//        $price->setMembership($membership);
//        $manager->persist($price);
//        $price = new ReferralPrice();
//        $price->setMinRef(1001);
//        $price->setMaxRef(1250);
//        $price->setMonthly(0.01);
//        $price->setAutopay(0.02);
//        $price->setMembership($membership);
//        $manager->persist($price);
//        $price = new ReferralPrice();
//        $price->setMinRef(1251);
//        $price->setMaxRef(1500);
//        $price->setMonthly(0.01);
//        $price->setAutopay(0.02);
//        $price->setMembership($membership);
//        $manager->persist($price);
//        $price = new ReferralPrice();
//        $price->setMinRef(1501);
//        $price->setMaxRef(1750);
//        $price->setMonthly(0.01);
//        $price->setAutopay(0.02);
//        $price->setMembership($membership);
//        $manager->persist($price);
//        $price = new ReferralPrice();
//        $price->setMinRef(1751);
//        $price->setMaxRef(10000);
//        $price->setMonthly(0.01);
//        $price->setAutopay(0.02);
//        $price->setMembership($membership);
//        $manager->persist($price);
//
//        $membership = new Membership();
//        $membership->setName('Try me');
//        $membership->setPrice(20.00);
//        $membership->setDuration(30);
//        $membership->setClick(75);
//        $membership->setVideoClick(75);
//        $membership->setPollClick(75);
//        $membership->setMaxClickInDay(0);
//        $membership->setMaxVideoClickInDay(0);
//        $membership->setMaxPollClickInDay(0);
//        $membership->setRefClick(40);
//        $membership->setRefVideoClick(40);
//        $membership->setRefPollClick(40);
//        $membership->setRefLimit(20);
//        $membership->setRentedRefLimit(450);
//        $membership->setInstPayment(false);
//        $membership->setPurchaseComission(0);
//        $membership->setUpgradeComission(0);
//        $membership->setRefDeletionCost(0);
//        $membership->setActive(true);
//        $manager->persist($membership);
//        $this->addReference('try_me', $membership);
//        $withdrawSettings = new WithdrawSettings();
//        $withdrawSettings->setMembership($membership);
//        $withdrawSettings->setCashoutTime(3);
//        $withdrawSettings->setMaxInDay(100);
//        $withdrawSettings->setMinPayout(10);
//        $manager->persist($withdrawSettings);
//        $rentReferral = new RentReferral();
//        $rentReferral->setMembership($membership);
//        $rentReferral->setRefLimit(0);
//        $rentReferral->setRefPack(5);
//        $rentReferral->setRecycleCost(10);
//        $rentReferral->setRefTime(3);
//        $manager->persist($rentReferral);
//        $price = new ReferralPrice();
//        $price->setMinRef(0);
//        $price->setMaxRef(250);
//        $price->setMonthly(0.01);
//        $price->setAutopay(0.02);
//        $price->setMembership($membership);
//        $manager->persist($price);
//        $price = new ReferralPrice();
//        $price->setMinRef(251);
//        $price->setMaxRef(500);
//        $price->setMonthly(0.01);
//        $price->setAutopay(0.02);
//        $price->setMembership($membership);
//        $manager->persist($price);
//        $price = new ReferralPrice();
//        $price->setMinRef(501);
//        $price->setMaxRef(750);
//        $price->setMonthly(0.01);
//        $price->setAutopay(0.02);
//        $price->setMembership($membership);
//        $manager->persist($price);
//        $price = new ReferralPrice();
//        $price->setMinRef(751);
//        $price->setMaxRef(1000);
//        $price->setMonthly(0.01);
//        $price->setAutopay(0.02);
//        $price->setMembership($membership);
//        $manager->persist($price);
//        $price = new ReferralPrice();
//        $price->setMinRef(1001);
//        $price->setMaxRef(1250);
//        $price->setMonthly(0.01);
//        $price->setAutopay(0.02);
//        $price->setMembership($membership);
//        $manager->persist($price);
//        $price = new ReferralPrice();
//        $price->setMinRef(1251);
//        $price->setMaxRef(1500);
//        $price->setMonthly(0.01);
//        $price->setAutopay(0.02);
//        $price->setMembership($membership);
//        $manager->persist($price);
//        $price = new ReferralPrice();
//        $price->setMinRef(1501);
//        $price->setMaxRef(1750);
//        $price->setMonthly(0.01);
//        $price->setAutopay(0.02);
//        $price->setMembership($membership);
//        $manager->persist($price);
//        $price = new ReferralPrice();
//        $price->setMinRef(1751);
//        $price->setMaxRef(10000);
//        $price->setMonthly(0.01);
//        $price->setAutopay(0.02);
//        $price->setMembership($membership);
//        $manager->persist($price);
//
//        $membership = new Membership();
//        $membership->setName('Cake');
//        $membership->setPrice(50.00);
//        $membership->setDuration(30);
//        $membership->setClick(100);
//        $membership->setVideoClick(100);
//        $membership->setPollClick(100);
//        $membership->setMaxClickInDay(0);
//        $membership->setMaxVideoClickInDay(0);
//        $membership->setMaxPollClickInDay(0);
//        $membership->setRefClick(40);
//        $membership->setRefVideoClick(40);
//        $membership->setRefPollClick(40);
//        $membership->setRefLimit(0);
//        $membership->setRentedRefLimit(500);
//        $membership->setInstPayment(false);
//        $membership->setPurchaseComission(0);
//        $membership->setUpgradeComission(0);
//        $membership->setRefDeletionCost(0);
//        $membership->setActive(true);
//        $manager->persist($membership);
//        $this->addReference('cake', $membership);
//        $withdrawSettings = new WithdrawSettings();
//        $withdrawSettings->setMembership($membership);
//        $withdrawSettings->setCashoutTime(3);
//        $withdrawSettings->setMaxInDay(100);
//        $withdrawSettings->setMinPayout(10);
//        $manager->persist($withdrawSettings);
//        $rentReferral = new RentReferral();
//        $rentReferral->setMembership($membership);
//        $rentReferral->setRefLimit(0);
//        $rentReferral->setRefPack(5);
//        $rentReferral->setRecycleCost(10);
//        $rentReferral->setRefTime(3);
//        $manager->persist($rentReferral);
//        $price = new ReferralPrice();
//        $price->setMinRef(0);
//        $price->setMaxRef(250);
//        $price->setMonthly(0.01);
//        $price->setAutopay(0.02);
//        $price->setMembership($membership);
//        $manager->persist($price);
//        $price = new ReferralPrice();
//        $price->setMinRef(251);
//        $price->setMaxRef(500);
//        $price->setMonthly(0.01);
//        $price->setAutopay(0.02);
//        $price->setMembership($membership);
//        $manager->persist($price);
//        $price = new ReferralPrice();
//        $price->setMinRef(501);
//        $price->setMaxRef(750);
//        $price->setMonthly(0.01);
//        $price->setAutopay(0.02);
//        $price->setMembership($membership);
//        $manager->persist($price);
//        $price = new ReferralPrice();
//        $price->setMinRef(751);
//        $price->setMaxRef(1000);
//        $price->setMonthly(0.01);
//        $price->setAutopay(0.02);
//        $price->setMembership($membership);
//        $manager->persist($price);
//        $price = new ReferralPrice();
//        $price->setMinRef(1001);
//        $price->setMaxRef(1250);
//        $price->setMonthly(0.01);
//        $price->setAutopay(0.02);
//        $price->setMembership($membership);
//        $manager->persist($price);
//        $price = new ReferralPrice();
//        $price->setMinRef(1251);
//        $price->setMaxRef(1500);
//        $price->setMonthly(0.01);
//        $price->setAutopay(0.02);
//        $price->setMembership($membership);
//        $manager->persist($price);
//        $price = new ReferralPrice();
//        $price->setMinRef(1501);
//        $price->setMaxRef(1750);
//        $price->setMonthly(0.01);
//        $price->setAutopay(0.02);
//        $price->setMembership($membership);
//        $manager->persist($price);
//        $price = new ReferralPrice();
//        $price->setMinRef(1751);
//        $price->setMaxRef(10000);
//        $price->setMonthly(0.01);
//        $price->setAutopay(0.02);
//        $price->setMembership($membership);
//        $manager->persist($price);
//
//        $membership = new Membership();
//        $membership->setName('Chocolate');
//        $membership->setPrice(100.00);
//        $membership->setDuration(30);
//        $membership->setClick(100);
//        $membership->setVideoClick(100);
//        $membership->setPollClick(100);
//        $membership->setMaxClickInDay(0);
//        $membership->setMaxVideoClickInDay(0);
//        $membership->setMaxPollClickInDay(0);
//        $membership->setRefClick(30);
//        $membership->setRefVideoClick(30);
//        $membership->setRefPollClick(30);
//        $membership->setRefLimit(0);
//        $membership->setRentedRefLimit(1000);
//        $membership->setInstPayment(false);
//        $membership->setPurchaseComission(0);
//        $membership->setUpgradeComission(0);
//        $membership->setRefDeletionCost(0);
//        $membership->setActive(true);
//        $manager->persist($membership);
//        $this->addReference('chocolate', $membership);
//        $withdrawSettings = new WithdrawSettings();
//        $withdrawSettings->setMembership($membership);
//        $withdrawSettings->setCashoutTime(3);
//        $withdrawSettings->setMaxInDay(100);
//        $withdrawSettings->setMinPayout(10);
//        $manager->persist($withdrawSettings);
//        $rentReferral = new RentReferral();
//        $rentReferral->setMembership($membership);
//        $rentReferral->setRefLimit(0);
//        $rentReferral->setRefPack(5);
//        $rentReferral->setRecycleCost(10);
//        $rentReferral->setRefTime(3);
//        $manager->persist($rentReferral);
//        $price = new ReferralPrice();
//        $price->setMinRef(0);
//        $price->setMaxRef(250);
//        $price->setMonthly(0.01);
//        $price->setAutopay(0.02);
//        $price->setMembership($membership);
//        $manager->persist($price);
//        $price = new ReferralPrice();
//        $price->setMinRef(251);
//        $price->setMaxRef(500);
//        $price->setMonthly(0.01);
//        $price->setAutopay(0.02);
//        $price->setMembership($membership);
//        $manager->persist($price);
//        $price = new ReferralPrice();
//        $price->setMinRef(501);
//        $price->setMaxRef(750);
//        $price->setMonthly(0.01);
//        $price->setAutopay(0.02);
//        $price->setMembership($membership);
//        $manager->persist($price);
//        $price = new ReferralPrice();
//        $price->setMinRef(751);
//        $price->setMaxRef(1000);
//        $price->setMonthly(0.01);
//        $price->setAutopay(0.02);
//        $price->setMembership($membership);
//        $manager->persist($price);
//        $price = new ReferralPrice();
//        $price->setMinRef(1001);
//        $price->setMaxRef(1250);
//        $price->setMonthly(0.01);
//        $price->setAutopay(0.02);
//        $price->setMembership($membership);
//        $manager->persist($price);
//        $price = new ReferralPrice();
//        $price->setMinRef(1251);
//        $price->setMaxRef(1500);
//        $price->setMonthly(0.01);
//        $price->setAutopay(0.02);
//        $price->setMembership($membership);
//        $manager->persist($price);
//        $price = new ReferralPrice();
//        $price->setMinRef(1501);
//        $price->setMaxRef(1750);
//        $price->setMonthly(0.01);
//        $price->setAutopay(0.02);
//        $price->setMembership($membership);
//        $manager->persist($price);
//        $price = new ReferralPrice();
//        $price->setMinRef(1751);
//        $price->setMaxRef(10000);
//        $price->setMonthly(0.01);
//        $price->setAutopay(0.02);
//        $price->setMembership($membership);
//        $manager->persist($price);
//
//        $membership = new Membership();
//        $membership->setName('Caramel');
//        $membership->setPrice(200.00);
//        $membership->setDuration(30);
//        $membership->setClick(100);
//        $membership->setVideoClick(100);
//        $membership->setPollClick(100);
//        $membership->setMaxClickInDay(0);
//        $membership->setMaxVideoClickInDay(0);
//        $membership->setMaxPollClickInDay(0);
//        $membership->setRefClick(40);
//        $membership->setRefVideoClick(40);
//        $membership->setRefPollClick(40);
//        $membership->setRefLimit(0);
//        $membership->setRentedRefLimit(1500);
//        $membership->setInstPayment(false);
//        $membership->setPurchaseComission(0);
//        $membership->setUpgradeComission(0);
//        $membership->setRefDeletionCost(0);
//        $membership->setActive(true);
//        $manager->persist($membership);
//        $this->addReference('caramel', $membership);
//        $withdrawSettings = new WithdrawSettings();
//        $withdrawSettings->setMembership($membership);
//        $withdrawSettings->setCashoutTime(3);
//        $withdrawSettings->setMaxInDay(100);
//        $withdrawSettings->setMinPayout(10);
//        $manager->persist($withdrawSettings);
//        $rentReferral = new RentReferral();
//        $rentReferral->setMembership($membership);
//        $rentReferral->setRefLimit(0);
//        $rentReferral->setRefPack(5);
//        $rentReferral->setRecycleCost(10);
//        $rentReferral->setRefTime(3);
//        $manager->persist($rentReferral);
//        $price = new ReferralPrice();
//        $price->setMinRef(0);
//        $price->setMaxRef(250);
//        $price->setMonthly(0.01);
//        $price->setAutopay(0.02);
//        $price->setMembership($membership);
//        $manager->persist($price);
//        $price = new ReferralPrice();
//        $price->setMinRef(251);
//        $price->setMaxRef(500);
//        $price->setMonthly(0.01);
//        $price->setAutopay(0.02);
//        $price->setMembership($membership);
//        $manager->persist($price);
//        $price = new ReferralPrice();
//        $price->setMinRef(501);
//        $price->setMaxRef(750);
//        $price->setMonthly(0.01);
//        $price->setAutopay(0.02);
//        $price->setMembership($membership);
//        $manager->persist($price);
//        $price = new ReferralPrice();
//        $price->setMinRef(751);
//        $price->setMaxRef(1000);
//        $price->setMonthly(0.01);
//        $price->setAutopay(0.02);
//        $price->setMembership($membership);
//        $manager->persist($price);
//        $price = new ReferralPrice();
//        $price->setMinRef(1001);
//        $price->setMaxRef(1250);
//        $price->setMonthly(0.01);
//        $price->setAutopay(0.02);
//        $price->setMembership($membership);
//        $manager->persist($price);
//        $price = new ReferralPrice();
//        $price->setMinRef(1251);
//        $price->setMaxRef(1500);
//        $price->setMonthly(0.01);
//        $price->setAutopay(0.02);
//        $price->setMembership($membership);
//        $manager->persist($price);
//        $price = new ReferralPrice();
//        $price->setMinRef(1501);
//        $price->setMaxRef(1750);
//        $price->setMonthly(0.01);
//        $price->setAutopay(0.02);
//        $price->setMembership($membership);
//        $manager->persist($price);
//        $price = new ReferralPrice();
//        $price->setMinRef(1751);
//        $price->setMaxRef(10000);
//        $price->setMonthly(0.01);
//        $price->setAutopay(0.02);
//        $price->setMembership($membership);
//        $manager->persist($price);
//
//        $membership = new Membership();
//        $membership->setName('Candy');
//        $membership->setPrice(400.00);
//        $membership->setDuration(30);
//        $membership->setClick(100);
//        $membership->setVideoClick(100);
//        $membership->setPollClick(100);
//        $membership->setMaxClickInDay(0);
//        $membership->setMaxVideoClickInDay(0);
//        $membership->setMaxPollClickInDay(0);
//        $membership->setRefClick(50);
//        $membership->setRefVideoClick(50);
//        $membership->setRefPollClick(50);
//        $membership->setRefLimit(0);
//        $membership->setRentedRefLimit(2500);
//        $membership->setInstPayment(false);
//        $membership->setPurchaseComission(0);
//        $membership->setUpgradeComission(0);
//        $membership->setRefDeletionCost(0);
//        $membership->setActive(true);
//        $manager->persist($membership);
//        $this->addReference('candy', $membership);
//        $withdrawSettings = new WithdrawSettings();
//        $withdrawSettings->setMembership($membership);
//        $withdrawSettings->setCashoutTime(3);
//        $withdrawSettings->setMaxInDay(100);
//        $withdrawSettings->setMinPayout(10);
//        $manager->persist($withdrawSettings);
//        $rentReferral = new RentReferral();
//        $rentReferral->setMembership($membership);
//        $rentReferral->setRefLimit(0);
//        $rentReferral->setRefPack(5);
//        $rentReferral->setRecycleCost(10);
//        $rentReferral->setRefTime(3);
//        $manager->persist($rentReferral);
//        $price = new ReferralPrice();
//        $price->setMinRef(0);
//        $price->setMaxRef(250);
//        $price->setMonthly(0.01);
//        $price->setAutopay(0.02);
//        $price->setMembership($membership);
//        $manager->persist($price);
//        $price = new ReferralPrice();
//        $price->setMinRef(251);
//        $price->setMaxRef(500);
//        $price->setMonthly(0.01);
//        $price->setAutopay(0.02);
//        $price->setMembership($membership);
//        $manager->persist($price);
//        $price = new ReferralPrice();
//        $price->setMinRef(501);
//        $price->setMaxRef(750);
//        $price->setMonthly(0.01);
//        $price->setAutopay(0.02);
//        $price->setMembership($membership);
//        $manager->persist($price);
//        $price = new ReferralPrice();
//        $price->setMinRef(751);
//        $price->setMaxRef(1000);
//        $price->setMonthly(0.01);
//        $price->setAutopay(0.02);
//        $price->setMembership($membership);
//        $manager->persist($price);
//        $price = new ReferralPrice();
//        $price->setMinRef(1001);
//        $price->setMaxRef(1250);
//        $price->setMonthly(0.01);
//        $price->setAutopay(0.02);
//        $price->setMembership($membership);
//        $manager->persist($price);
//        $price = new ReferralPrice();
//        $price->setMinRef(1251);
//        $price->setMaxRef(1500);
//        $price->setMonthly(0.01);
//        $price->setAutopay(0.02);
//        $price->setMembership($membership);
//        $manager->persist($price);
//        $price = new ReferralPrice();
//        $price->setMinRef(1501);
//        $price->setMaxRef(1750);
//        $price->setMonthly(0.01);
//        $price->setAutopay(0.02);
//        $price->setMembership($membership);
//        $manager->persist($price);
//        $price = new ReferralPrice();
//        $price->setMinRef(1751);
//        $price->setMaxRef(10000);
//        $price->setMonthly(0.01);
//        $price->setAutopay(0.02);
//        $price->setMembership($membership);
//        $manager->persist($price);
//
//        $membership = new Membership();
//        $membership->setName('Sweet');
//        $membership->setPrice(500.00);
//        $membership->setDuration(15);
//        $membership->setClick(100);
//        $membership->setVideoClick(100);
//        $membership->setPollClick(100);
//        $membership->setMaxClickInDay(0);
//        $membership->setMaxVideoClickInDay(0);
//        $membership->setMaxPollClickInDay(0);
//        $membership->setRefClick(50);
//        $membership->setRefVideoClick(50);
//        $membership->setRefPollClick(50);
//        $membership->setRefLimit(0);
//        $membership->setRentedRefLimit(2500);
//        $membership->setInstPayment(false);
//        $membership->setPurchaseComission(0);
//        $membership->setUpgradeComission(0);
//        $membership->setRefDeletionCost(0);
//        $membership->setActive(true);
//        $manager->persist($membership);
//        $this->addReference('sweet', $membership);
//        $withdrawSettings = new WithdrawSettings();
//        $withdrawSettings->setMembership($membership);
//        $withdrawSettings->setCashoutTime(3);
//        $withdrawSettings->setMaxInDay(100);
//        $withdrawSettings->setMinPayout(10);
//        $manager->persist($withdrawSettings);
//        $rentReferral = new RentReferral();
//        $rentReferral->setMembership($membership);
//        $rentReferral->setRefLimit(0);
//        $rentReferral->setRefPack(5);
//        $rentReferral->setRecycleCost(10);
//        $rentReferral->setRefTime(3);
//        $manager->persist($rentReferral);
//        $price = new ReferralPrice();
//        $price->setMinRef(0);
//        $price->setMaxRef(250);
//        $price->setMonthly(0.01);
//        $price->setAutopay(0.02);
//        $price->setMembership($membership);
//        $manager->persist($price);
//        $price = new ReferralPrice();
//        $price->setMinRef(251);
//        $price->setMaxRef(500);
//        $price->setMonthly(0.01);
//        $price->setAutopay(0.02);
//        $price->setMembership($membership);
//        $manager->persist($price);
//        $price = new ReferralPrice();
//        $price->setMinRef(501);
//        $price->setMaxRef(750);
//        $price->setMonthly(0.01);
//        $price->setAutopay(0.02);
//        $price->setMembership($membership);
//        $manager->persist($price);
//        $price = new ReferralPrice();
//        $price->setMinRef(751);
//        $price->setMaxRef(1000);
//        $price->setMonthly(0.01);
//        $price->setAutopay(0.02);
//        $price->setMembership($membership);
//        $manager->persist($price);
//        $price = new ReferralPrice();
//        $price->setMinRef(1001);
//        $price->setMaxRef(1250);
//        $price->setMonthly(0.01);
//        $price->setAutopay(0.02);
//        $price->setMembership($membership);
//        $manager->persist($price);
//        $price = new ReferralPrice();
//        $price->setMinRef(1251);
//        $price->setMaxRef(1500);
//        $price->setMonthly(0.01);
//        $price->setAutopay(0.02);
//        $price->setMembership($membership);
//        $manager->persist($price);
//        $price = new ReferralPrice();
//        $price->setMinRef(1501);
//        $price->setMaxRef(1750);
//        $price->setMonthly(0.01);
//        $price->setAutopay(0.02);
//        $price->setMembership($membership);
//        $manager->persist($price);
//        $price = new ReferralPrice();
//        $price->setMinRef(1751);
//        $price->setMaxRef(10000);
//        $price->setMonthly(0.01);
//        $price->setAutopay(0.02);
//        $price->setMembership($membership);
//        $manager->persist($price);
//
//        $manager->flush();
    }

    /**
     * {@inheritDoc}
     */
    public function getOrder()
    {
        return 1;
    }
}